### ISSUE TITLE
Exception cannot find co

### ISSUE THREAD

**Issue by denisvlah** [munyabe/CaseConverter#1]
When the extension is installed from Visual Studio Glery, it doesn't work when invoked. 
A message box with error message is displayed. It points to the exception log.

This is a entry from Visual Studio Exception Log:

<entry>
    <record>770</record>
    <time>2016/02/29 10:15:13.166</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [CaseConverterPackage]</description>
    <guid>{3293CB25-75B9-4D5A-A248-EA3CF25FC4C8}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>

**Comment by munyabe** [comment]
Thank you for the information.

This is the issue on this extension. I could replicate the same exception.
I think that Visual Studio 2015 is not installed in your machine.
Just a moment, I'll fix it.

**Comment by munyabe** [comment]
This issue should be fixed at v1.1. Please update the extension and let me know how it goes.

**Comment by denisvlah** [comment]
Thank you for your fix. It works now in Visual 2013.
It is very helpful.
