### ISSUE TITLE
COMException dialog when launched in VS 2015

### ISSUE THREAD

**Issue by BrainCrumbz** [munyabe/CaseConverter#2]
Just installed in VS2015 Community Ed. & restarted on a Win 10 64bit machine that also has VS 2013 Community Ed. and VS Code. While cursor is on a word (word not selected), as soon as key binding is pressed (CTRL+SHIFT+K, CTRL+SHIFT+C), following error dialog shows and nothin happens to underlying text:

![comexception](https://cloud.githubusercontent.com/assets/3185573/15182901/0703f27e-178f-11e6-9cc8-bbd86d8ef718.png)

Are we doing anything wrong? Thank you

**Comment by munyabe** [comment]
Thanks for your reporting!
I've confirmed the issue. This is a simple bug...
I'll fix and updated version will be released in a few days.

**Comment by munyabe** [comment]
I have made a new release now! Please update from gallery.

**Comment by BrainCrumbz** [comment]
Just got notified by means of VS Notifications & updated. Now when no word is selected, it does nothing (and it does not throw error of course!).

It could be a nice-to-have feature if extension could detect the _word_ underneath cursor, when nothing is selected. Basically the same happening as when you press F2 to perform rename refactoring. Just our 2 cents. Thank you!

**Comment by munyabe** [comment]
Sounds good! I opened the new issue #3 .
Let's see if we can get this suggestion to vNext.
